table DimInstitucion
	lineageTag: 0b06876b-d595-4219-9fb1-531188df0ff7

	column InstitucionID
		dataType: string
		isHidden
		lineageTag: 407ecc3a-67ce-4a69-86f0-8bb1063799c9
		summarizeBy: none
		sourceColumn: InstitucionID

	column Institucion
		dataType: string
		lineageTag: 6d18f539-d3eb-4caf-88f0-9f37125f1a76
		summarizeBy: none
		sourceColumn: Institucion

	partition DimInstitucion = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(#"Ruta datos" & "/dim_institucion.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Types = Table.TransformColumnTypes(Headers,{{"InstitucionID",type text},{"Institucion",type text}},"en-US")
				in Types

